version: '3.8'

services:
  # Database
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
  
  # for slurm's database
  mysql:
    image: mariadb:10.10
    container_name: mysql
    hostname: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql:/var/lib/mysql


  # Redis
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "${REDIS_PORT}:6379"

  # Slurm Cluster
  slurm:
    image: giovtorres/slurm-docker-cluster:latest
    container_name: slurm_cluster
    hostname: slurmctl
    ports:
      - "2222:22"
    volumes:
      - ./oj_data:/data
    environment:
      - SLURM_Create_User=yes
      - SLURM_User=admin
      - SLURM_Password=admin
    depends_on:
      - mysql

  # Web Server (FastAPI)
  backend:
    build: .
    volumes:
      - .:/app
      - ./oj_data:/data
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_SERVER}:${POSTGRES_PORT}/${POSTGRES_DB}
      - REDIS_URL=redis://${REDIS_HOST}:${REDIS_PORT}/0
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - DATA_DIR=/data
    depends_on:
      - db
      - redis

  # Celery Worker
  worker:
    build: .
    command: watchfiles "celery -A app.core.celery_app worker --loglevel=info"
    volumes:
      - .:/app
      - ./oj_data:/data
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_SERVER}:${POSTGRES_PORT}/${POSTGRES_DB}
      - REDIS_URL=redis://${REDIS_HOST}:${REDIS_PORT}/0
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - DATA_DIR=/data
      - SLURM_HOST=slurm 
      - SLURM_USER=admin
      - SLURM_PASSWORD=admin
    depends_on:
      - db
      - redis
      - slurm

volumes:
  postgres_data:
  var_lib_mysql: