name: poj_backend  # Parallel OJ Backend
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    # Web Framework
    - fastapi
    - uvicorn[standard]
    - python-multipart

    # Database (ORM & Migration)
    - sqlalchemy
    - alembic
    - psycopg2-binary
    - asyncpg

    # Data Validation & Settings
    - pydantic
    - pydantic-settings
    - email-validator

    # Security
    - python-jose[cryptography]
    - passlib[bcrypt]
    - bcrypt==4.0.1

    # Async Task Queue
    - celery[redis]
    - watchfiles

    # Testing
    - pytest
    - httpx