name: poj_backend  # Parallel OJ Backend
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    # Web Framework
    - fastapi
    - uvicorn[standard]
    - python-multipart

    # Database (ORM & Migration)
    - sqlalchemy
    - alembic
    - psycopg2-binary   # PostgreSQL driver
    - asyncpg           # Async PostgreSQL driver

    # Data Validation & Settings
    - pydantic
    - pydantic-settings
    - email-validator

    # Security
    - python-jose[cryptography]  # JWT
    - passlib[bcrypt]            # Password Hashing
    - bcrypt==4.0.1

    # Redis (for Message Queue)
    - redis

    # Testing
    - pytest
    - httpx